-- CATEGORY
CREATE TABLE categories(
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50),description VARCHAR(150),
    estado TINYINT(1)
);

-- TRADEMARK
CREATE TABLE trademarks(
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50),description VARCHAR(150),
    estado TINYINT(1)
);

-- ITEM

CREATE TABLE products(
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  family_id INT NOT NULL,
  internal_id VARCHAR(10),name VARCHAR(150),
  price DECIMAL(12,4),estado TINYINT(1)
);



